### ISSUE TITLE
Reject Declaration request Endpoint

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#617] opened 2017-07-14 07:34 UTC
As a Any MSP user that has scope `declaration_request:reject`
I want to be able to reject declaration requests that hasn't been signed yet
So that I can clean it up in case of mistakes

[spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/reject-declaration-request)

**Comment by gmile** [comment] 2017-07-19 08:58
I could not locate BPM(N) spec in confluence, meaning I will assume a few things here until the spec appears or someone points me to one:

* the status of declaration request will be changed to "REJECTED",
* response to this call will be rendering of entire declaration request, including newly set status.

**Comment by gmile** [comment] 2017-07-19 09:08
@TarasenkoA @lymychp spec on confluence, specifically "Response" part, seems to completely off:

![image](https://user-images.githubusercontent.com/207112/28359473-f631ecac-6c7a-11e7-88ab-6de64ff0a87c.png)

Please fix it.

**Comment by gmile** [comment] 2017-07-19 11:59
This is done in https://github.com/Nebo15/ehealth.api/pull/660

**Comment by gmile** [comment] 2017-07-19 11:59
Needs testing!

**Comment by TarasenkoA** [comment] 2017-07-20 08:05
when I try to send declaration request to reject - I have error with code 404

request:
```
curl -X PATCH \
  http://dev.ehealth.world/api/declaration_requests/67b2ec16-22da-4d86-a6c9-3fc3a7c7052a/actions/reject \
  -H 'authorization: Bearer NUJ6S1FvN3lyL1BKNGcrbHE4eTFpdz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 3212ba2f-69d0-b666-44d0-6e32ba3f1cc7'
```

responce:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/declaration_requests/67b2ec16-22da-4d86-a6c9-3fc3a7c7052a/actions/reject",
        "type": "object",
        "request_id": "p1vrul2ev6tjlpepccevjt5iv3b1e2ej",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}
```

User have scope `declaration_request:reject`.  Maybe trouble with route?

**Comment by gmile** [comment] 2017-07-20 08:15
Need to add route, yes.

**Comment by gmile** [comment] 2017-07-20 10:44
@TarasenkoA a route was added in https://github.com/Nebo15/ehealth.k8s/commit/31b186a0476fcec4ae65673681ebe180d14980b1, please review it.

After trying your request I get 401 error, meaning the route now works but requires correct token.

Since the problem is solved, I'm closing this.

**Comment by TarasenkoA** [comment] 2017-07-20 12:22
Request work in one case - correct ID and status declaration, but in another cases:

in case when I try to send first request - status of declaration request change to "CANCELLED" but we need "REJECTED" status

in case when I try to send request at the second time - I have 404 code in response but correct code will be - 409

**Comment by gmile** [comment] 2017-07-20 12:44
@TarasenkoA I will fix both cases, thanks.

Separately, can you show me a list of all valid declaration_request statuses?

**Closed** 2017-07-20 15:32 UTC
Labels: epic/declaration, kind/user_story, status/todo
